name: Subs and Stuff Boston
favicon: null
layout_spectrum: 0.8322665025480092
typography_spectrum: 0.6895018159411848
title: Subs and Stuff Boston
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.894159950548783
  lightness: 0.7102303276769817
  saturation: 0.5186615022830665
  rhythmicContrast: 0.6622202573344111
purpose: []
