name: Subs and Stuff Boston
favicon: null
layout_spectrum: 0.85985
typography_spectrum: 0.54304
title: Subs and Stuff Boston
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000002'
    - '#78b5d1'
    - '#ffb582'
    - '#8c0400'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
